spring:
  config:
    import: "optional:configserver:"
  application:
    name: product
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
      username: username
      password: password
      retry:
        multiplier: 1.3
        max-attempts: 8
        max-interval: 5000
        initial-interval: 1000

